### ISSUE TITLE
Export to PDF does not show formatting

### ISSUE THREAD

**Issue by dgreen** [lijyze/obsidian-advanced-codeblock#2]
The extra formatting does not appear when one does an Export to PDF.

```
/**
 * Test
 */

package net.gwizlabs.test;

public class Test {
  private int x;
}
```

Looks like this in reading mode:

<img width="704" alt="Screen Shot 2022-06-04 at 4 44 21 PM" src="https://user-images.githubusercontent.com/7027/172026356-c3428b04-fc8f-4f6e-8eb3-4336611fd887.png">

Doing CMD+P Export to PDF while in reading mode shows

<img width="567" alt="Screen Shot 2022-06-04 at 4 45 44 PM" src="https://user-images.githubusercontent.com/7027/172026439-612dadd9-4724-41e3-b72b-0fca161a715e.png">

**Comment by lijyze** [comment]
This seems can not be implemented.

The functionality export to pdf seems only care about static page elements. I'm not sure if it's indeed, I get this result from tests of mine.

While line number or highlight lines have to be added dynamically. Because you can only know the style of the specific code block after it have been mounted to document and only if you know that style you can make additional components display correctly.
